font_family Iosevka Nerd Font
font_family Iosevka

hide_window_decorations titlebar-and-corners
font_size 20
adjust_line_height 0

background_opacity 0.9

cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.05
cursor_shape block
cursor_blink true

confirm_os_window_close 0

foreground #d0d0d0
background #282a36
color0     #1c252c
color8     #384148
color1     #e05f65
color9     #fc7b81
color2     #78dba9
color10    #94f7c5
color3     #f1cf8a
color11    #ffeba6
color4     #70a5eb
color12    #8cc1ff
color5     #e28dc6
color13    #ebadd6
color6     #74bee9
color14    #90daff
color7     #dee1e6
color15    #fafdff
