# ==================================================
# => ESSENTIALS
# ==================================================
set -sg escape-time 0

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g set-clipboard on
set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on   
set -g mode-keys vi

# ==================================================
# => BINDINGS
# ==================================================
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# source file
bind C-r source-file "~/.config/tmux/tmux.conf" \; display " sourced tmux"

# github script
bind g run "bash ~/.config/scripts/github.sh '#{pane_current_path}'"

# display session list & switch to new session
bind C-s display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \" |
    ^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"

# window commands
bind \\  split-window -h -c "#{pane_current_path}"
bind -   split-window -v -c "#{pane_current_path}"
bind c   new-window      -c "#{pane_current_path}"
bind C-n next-window
bind C-p previous-window

# ==================================================
# => STATUS BAR / DISPLAY
# ==================================================
set -g status-position top
set -g status-justify absolute-centre
set -g status-interval 5

# set -g status-left "#S"
set -g status-left '#[fg=#00e68a,bold] #S'
set -g status-right ""
set -g status-style "bg=default"

set -g window-status-current-style "fg=default bg=white  "
setw -g window-status-format ' #I:#W '
setw -g window-status-current-format '#[fg=black,bold] #I:#W '

set -g pane-border-style 'fg=#30363d'
set -g pane-active-border-style 'fg=#00e68a'

set -g message-style 'bg=#00e68a fg=black bold'

# ==================================================
# => PLUG PLUG
# ==================================================
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
