highlight_color = "LightBlue"
cursor = "█"
terminal_launcher = "kitty -e"
hard_stop = false

rounded_borders = false

main_border_color = "White"
apps_border_color = "White"
input_border_color = "White"

main_text_color = "White"
apps_text_color = "White"
input_text_color = "White"

fancy_mode = false

header_title_color = "White"

# hide top panel
title_panel_height_percent = 1
input_panel_height = 3
